const assert = require('node:assert/strict');
const fs = require('node:fs');
const vm = require('node:vm');
const source = fs.readFileSync(require.resolve('../game.js'), 'utf8');
const start = source.indexOf('    updateAutoDoors()');
const end = source.indexOf('    updateAutoChests()', start);
const Scene = vm.runInNewContext(`(class {${source.slice(start,end)}})`, {TILE:16});
const scene = new Scene();
scene.player={x:100,y:125};scene.state={bossUnlocked:false,doorOpened:false};
const door={sprite:{active:true,x:100,y:100},opened:false,animating:false};
scene.roomDoors=[door];let opened=0,closed=0,boss=0,occupied=false;
scene.openRoomDoor=()=>opened++;scene.closeRoomDoor=()=>closed++;scene.openDoor=()=>boss++;
scene.doorwayOccupied=()=>occupied;
scene.updateAutoDoors();assert.equal(opened,1);
door.animating=true;scene.updateAutoDoors();assert.equal(opened,1);
door.animating=false;door.opened=true;scene.player.y=145;scene.updateAutoDoors();assert.equal(closed,0);
scene.player.y=180;occupied=true;scene.updateAutoDoors();assert.equal(closed,0);
occupied=false;scene.updateAutoDoors();assert.equal(closed,1);
scene.door={active:true,x:100,y:180};scene.updateAutoDoors();assert.equal(boss,0);
scene.state.bossUnlocked=true;scene.updateAutoDoors();assert.equal(boss,1);
scene.gateAnimating=true;scene.updateAutoDoors();assert.equal(boss,1);
assert(!source.includes('E · ATVĒRT TELPAS DURVIS'));
assert(!source.includes('E · ATVĒRT BOSA DURVIS'));
console.log('Automatic doors passed: approach, distance hysteresis, occupied doorway, animation guard, boss kill gate.');
