const fs = require('node:fs');
const vm = require('node:vm');
const assert = require('node:assert/strict');
const { EventEmitter } = require('node:events');
const source = fs.readFileSync(require.resolve('../game.js'), 'utf8');
const methods = source.slice(source.indexOf('    doorwayOccupied('), source.indexOf('    addWallTorch('));
const Scene = vm.runInNewContext(`(class { ${methods} })`, { sound: { blip() {} } });
const scene = new Scene();
scene.updateFogOfWar = scene.updateHud = scene.showLootToast = () => {};
scene.enemies = { getChildren: () => [] };
scene.player = { active: true, body: { enable: true, x: 0, right: 10, y: 0, bottom: 10 } };
const sprite = new EventEmitter();
sprite.active = true;
sprite.body = { x: 100, right: 132, y: 100, bottom: 116, enable: true };
sprite.setData = () => sprite;
sprite.play = (animation) => { sprite.animation = animation; };
const door = { sprite, opened: false, animating: false };
scene.openRoomDoor(door);
assert.equal(door.animating, true);
assert.equal(door.opened, false);
assert.equal(sprite.body.enable, true, 'Collider stays shut while leaves open');
scene.openRoomDoor(door);
assert.equal(sprite.listenerCount('animationcomplete'), 1, 'Repeated interaction cannot stack callbacks');
sprite.emit('animationcomplete');
assert.equal(door.opened, true);
assert.equal(sprite.body.enable, false);
scene.player.body = { enable: true, x: 110, right: 120, y: 104, bottom: 113 };
scene.closeRoomDoor(door);
assert.equal(door.animating, false, 'Do not close on a player in the doorway');
scene.player.active = false;
scene.closeRoomDoor(door);
assert.equal(sprite.animation, 'ash-door-close');
scene.player.active = true;
sprite.emit('animationcomplete');
assert.equal(sprite.animation, 'ash-door-open', 'Reopen if an actor enters mid-close');
assert.equal(sprite.body.enable, false);
sprite.emit('animationcomplete');
scene.player.active = false;
scene.closeRoomDoor(door);
sprite.emit('animationcomplete');
assert.equal(door.opened, false);
assert.equal(sprite.body.enable, true);
for (const [prefix, count] of [['door', 8], ['torch', 4]]) {
  for (let i = 0; i < count; i++) assert(fs.existsSync(require.resolve(`../assets/frames/ash_${prefix}_f${i}.png`)));
}
console.log('Door animation tests passed: transition timing, repeated input, safe closing, and all 12 assets.');
